### PR TITLE
Compile on OTP 19.0

### PR DESCRIPTION
**Pull request by michaelklishin**
Part of https://github.com/rabbitmq/rabbitmq-server/issues/860.

There are two primary changes:

 * Type spec syntax (backwards compatible)
 * `rand` is used instead of `random`

### CODE REVIEW

**Comment by michaelklishin** [comment]
OK, apparently the `rand` module is only [available in `18.0+`](https://github.com/erlang/otp/commit/95aff702b5e4b21ec277b1e0125f639ce30f997a), so this needs more work.

**Comment by michaelklishin** [comment]
@dumbbell thank you, this now needs merging into master.

**Comment by dumbbell** [comment]
This PR is merged to master.

**Comment by binarin** [comment]
Now it fails to build on older erlangs (i.e. 18.3.4) with
```
src/pmon.erl:43: referring to built-in type dict as a remote type; please take out the module name
```

**Comment by binarin** [comment]
Ah, sorry, I was accidentally using R16B03

**Pull request merged**
