### PR TITLE
Add function to allow setting timeout on multicall

### PR DESCRIPTION
**Pull request by lukebakken**
A timeout will be handled as an empty result.

@michaelklishin - should that be logged?

### CODE REVIEW

**Comment by michaelklishin** [comment]
It should be logged by the callers IMO.

**Comment by lukebakken** [comment]
Actually it looks like `{badrpc, _}` is "ignored" by returning an empty list so I think we're OK to ignore a timeout at this point.

**Comment by michaelklishin** [comment]
Merged manually.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.

**Pull request closed without merging**
