### PR TITLE
include/rabbit.hrl: Bump Erlang requirement to 19.3 (ERTS 8.3)

### PR DESCRIPTION
**Pull request by dumbbell**
[#152067396]

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@dumbbell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=234)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=234) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dumbbell Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=234)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=234) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dumbbell Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=234)!

**Comment by michaelklishin** [comment]
We decided to go with 19.3 because it's the first release series with correct correct UNIX signal handling in some cases and we'd like to be able to depend on that in, say, CLI tools at some point in the future.

**Pull request merged**
