### PR TITLE
Add erlang.mk query-deps

### PR DESCRIPTION
**Pull request by gerhard**
Before I update erlang.mk across all repos, wanted to double-check that this works for you @dumbbell on FreeBSD. Maybe @lukebakken or @acogoluegnes would like to weigh in with their Linux perspectives. This is the output that I'm getting in `deps/rabbit`:

```
make query-deps
rabbit: rabbitmq_cli git_rmq https://github.com/rabbitmq/rabbitmq-cli master
rabbit: syslog git https://github.com/schlagert/syslog 3.4.5
rabbit: cuttlefish hex https://hex.pm/packages/cuttlefish 2.2.0
rabbit: ranch hex https://hex.pm/packages/ranch 1.7.1
rabbit: lager hex https://hex.pm/packages/lager 3.8.0
rabbit: rabbit_common git_rmq https://github.com/rabbitmq/rabbitmq-common master
rabbit: ra git https://github.com/rabbitmq/ra.git master
rabbit: sysmon_handler hex https://hex.pm/packages/sysmon_handler 1.2.0
rabbit: stdout_formatter hex https://hex.pm/packages/stdout_formatter 0.2.2
rabbit: recon hex https://hex.pm/packages/recon 2.5.0
rabbit: observer_cli hex https://hex.pm/packages/observer_cli 1.5.3
rabbitmq_cli: rabbit_common git_rmq https://github.com/rabbitmq/rabbitmq-common master
rabbitmq_cli: observer_cli hex https://hex.pm/packages/observer_cli 1.5.3
rabbit_common: rabbitmq_codegen git_rmq https://github.com/rabbitmq/rabbitmq-codegen master
rabbit_common: lager hex https://hex.pm/packages/lager 3.8.0
rabbit_common: jsx hex https://hex.pm/packages/jsx 2.9.0
rabbit_common: ranch hex https://hex.pm/packages/ranch 1.7.1
rabbit_common: recon hex https://hex.pm/packages/recon 2.5.0
rabbit_common: credentials_obfuscation hex https://hex.pm/packages/credentials_obfuscation 1.1.0
lager: goldrush git https://github.com/DeadZen/goldrush.git 0.1.9
observer_cli: recon hex https://hex.pm/packages/recon 2.5.0
cuttlefish: getopt hex https://hex.pm/packages/getopt 1.0.1
cuttlefish: lager hex https://hex.pm/packages/lager 3.7.0
ra: elvis_mk git https://github.com/inaka/elvis.mk.git master
ra: aten hex https://hex.pm/packages/aten 0.5.3
ra: gen_batch_server hex https://hex.pm/packages/gen_batch_server 0.8.2
```

[Let me know if you have any questions](https://twitter.com/GIL_trainee/status/1229924637074690048/photo/1)

cc @essen re https://github.com/ninenines/erlang.mk/pull/875

### CODE REVIEW

**Comment by lukebakken** [comment]
Works on my Debian Buster VM - 
[query-deps-output-from-rabbit_common.txt](https://github.com/rabbitmq/rabbitmq-common/files/4293704/query-deps-output-from-rabbit_common.txt)

I'm assuming the list is short because the only `erlang.mk` change at this time is in this repository.

**Comment by gerhard** [comment]
> I'm assuming the list is short because the only `erlang.mk` change at this time is in this repository.

Follow the instructions in the commit message and let me know how it goes 😉

**Comment by lukebakken** [comment]
Yep, works as described. Thanks @gerhard

**Comment by gerhard** [comment]
@dumbbell if you can see any change in erlang.mk that should not be merged, shout, otherwise this is going in like the Eurostar arriving at St Pancras, from Paris 🚄

**Comment by gerhard** [comment]
Reminder to back-port this to `v3.8.x` after all `v3.9.x` builds pass. Reference this PR in that commit to verify.

**Pull request merged**
