### PR TITLE
Quorum queues

### PR DESCRIPTION
**Pull request by kjnilsson**
See: https://github.com/rabbitmq/rabbitmq-server/pull/1706

### CODE REVIEW

**Comment by hairyhum** [comment]
It looks like some changes are unrelated to the quorum queue, like `connection_churn_metrics`. Should this branch be merged with master?

**Comment by michaelklishin** [comment]
This branch will only be merged into master. It had `stable` merged into it to reduce delta (the QQ branches tend to go out of date during to their age).

**Comment by michaelklishin** [comment]
QQ branches had `master`/`stable` (in the docs) merged into them to reduce the delta. I'm not sure what the suggestion is, they are going to be merged into master soon.

**Comment by hairyhum** [comment]
It would be nice to see the actual changes without noise.

**Pull request merged**
