### PR TITLE
Update the supervisor2 module to use recent OTP as a base

### PR DESCRIPTION
**Pull request by lukebakken**
I recommend reviewing while ignoring white space:

https://github.com/rabbitmq/rabbitmq-common/pull/411/files?w=1

Fixes https://github.com/rabbitmq/rabbitmq-mqtt/issues/240

### CODE REVIEW

**Comment by lukebakken** [comment]
I still get some errors when running the entire `rabbitmq-server` CT tests (like connection tracking in the `vhost` suite) but I think they are unrelated to these changes.

**Review by michaelklishin — CHANGES_REQUESTED** [review]
I tried the following script that used to trigger a Erlang connection process leak in the MQTT plugin and the leaking is back with this branch:

``` python
#!/usr/bin/env python3

import paho.mqtt.client as mqtt
import random
import threading
import time


def random_sleep():
    time.sleep(random.randint(1,3))

def on_connect(client, userdata, flags, rc):
    client.subscribe("a/b/c", qos=0)
    client.unsubscribe("a/b/c")
    random_sleep()
    client.disconnect()


def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))


def on_disconnect(client, userdata, rc):
    if rc == 0:
        print('Disconnect success!')
        random_sleep()
        print('Thread exiting...')
    else:
        print('Unexpected disconnection: {}'.format(rc))


def connect(i):
    client = mqtt.Client(client_id="py-{}".format(i))
    client.on_connect = on_connect
    client.on_message = on_message
    client.on_disconnect = on_disconnect
    client.username_pw_set("guest", "guest")
    client.connect(host="localhost", port=1883, keepalive=6)
    print("Client {} has connected succesesfully".format(i))
    client.loop_forever()

for batch in range(8):
    print('Starting batch: {}'.format(batch))
    threads = []
    for i in range(8):
        t = threading.Thread(target=connect, args=[i])
        t.start()
        threads.append(t)

    for t in threads:
        t.join()
```

After 10 runs in a row, and a minute of cool down time, the number of Erlang processes on the node is over 10K vs. 600 or so when the node finished booting:

Screen Shot 2020-09-26 at 08 02 54

**Comment by michaelklishin** [comment]
``` shell
gmake ct-per_user_connection_channel_limit; gmake ct-per_vhost_connection_limit
```

fails on this branch but not with `master`.

**Comment by lukebakken** [comment]
@michaelklishin somehow I missed that you had reviewed this. I'll look into it.

**Comment by lukebakken** [comment]
@michaelklishin turns out the fix for that is simple. I'm just reducing some log spam at the moment, and will add a test for the `intrinsic` type.

**Comment by lukebakken** [comment]
@michaelklishin thanks again for double-checking. Ready for another review.

Also see the test added for the `intrinsic` type here: https://github.com/rabbitmq/rabbitmq-server/pull/2457

**Review by michaelklishin — APPROVED** [review]

**Comment by michaelklishin** [comment]
Let's wait for a week or two before backporting.

**Comment by michaelklishin** [comment]
Follow-up changes: a6bcdae2bb176a32edd35d5fbe2480e82497ccbc (cannot be cherry-picked, some changes are unrelated, so has to be applied manually).

**Pull request merged**
