### PR TITLE
Fix incorrect typespecs

### PR DESCRIPTION
**Pull request by jesperes**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@jesperes Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=358)!

[Click here](https://cla.pivotal.io/sync/rabbitmq?repositoryId=rabbitmq/rabbitmq-common&pullRequestId=358) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by lukebakken** [comment]
It seems that this pull request was opened in error due to the type and number of changes in it. Based on the title and branch name, it appears there should only be dialyzer changes in it. Closing and we'll keep an eye out for what should have been the intended changes.

**Comment by jesperes** [comment]
Yes, sorry about this. This PR was opened against the wrong repo.

**Comment by lukebakken** [comment]
No worries!

**Pull request closed without merging**
