### PR TITLE
Unsigned field types to support AMQP-0-9-1

### PR DESCRIPTION
**Pull request by hairyhum**
Added few unsigned types for better compatibility with AMQP-0-9-1
https://github.com/rabbitmq/rabbitmq-server/issues/20

### CODE REVIEW

**Comment by deadtrickster** [comment]
Hey! any plans for unsigned long? (uint64). what letter it could be assigned to?

**Comment by michaelklishin** [comment]
@deadtrickster is there really much use in supporting unsigned longs in attribute tables? FWIW most popular languages today don't support (or see widely used) unsigned anything these days.

**Comment by deadtrickster** [comment]
@michaelklishin Right now I can came up only with 64-bit pointers and monitoring examples. Pointers probably not relevant here :-) But say I want to monitor server(s) (or other monitorable thing) including memory and network usage. Values probably exceed uint32 very quickly. Of course data can go through message body but what if I also have nice custom header-like exchange that routs bad behaved stuff to emergency queue :-)

**Comment by hairyhum** [comment]
@deadtrickster there can be confusion if we add unsigned long, because it's field type tag already used for signed long (See http://www.rabbitmq.com/amqp-0-9-1-errata.html).

**Pull request merged**
